<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ajay-PC" name="Login Test" tests="2" failures="1" timestamp="4 Jul 2017 04:30:07 GMT" time="164.863" errors="0">
  <testcase name="doLogin" time="64.783" classname="com.abtrading.zoho.project.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="Login Test Failed.">
      <![CDATA[java.lang.AssertionError: Login Test Failed.
	at com.abtrading.zoho.project.base.BaseTest.reportFail(BaseTest.java:274)
	at com.abtrading.zoho.project.testcases.LoginTest.doLogin(LoginTest.java:57)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- doLogin -->
  <testcase name="doLogin" time="157.929" classname="com.abtrading.zoho.project.testcases.LoginTest"/>
</testsuite> <!-- Login Test -->
